version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - $PWD/public:/usr/share/nginx/html
    restart: always
    ports:
      - 80:80

  node:
    image: node:alpine
    volumes:
      - $PWD:/app
    working_dir: /app
    command: sh -c "npm i && npm run build"
