version: '3'

volumes:
  db-data:

services:
  phalcon:
    build:
      context: .
      dockerfile: ./build/prod/phalcon/Dockerfile
    volumes:
      - $PWD/src:/var/www
    networks:
      default:
        aliases:
          - backend

  db:
    image: postgres:10.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

  nginx:
    build:
      context: .
      dockerfile: ./build/prod/nginx/Dockerfile
    volumes:
      - $PWD/frontend/public:/var/www
    networks:
      - default
    