version: '3'

services:
  server:
    image: erlang:20-alpine
    working_dir: /app
    volumes:
      - $PWD:/app
    command: sh -c "erlc ./start.erl && erl -noshell -s start start"
    ports:
      - 80:80
